{
 "title": "Docker Containers Stats",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cname",
    "label": "container name",
    "query": {
     "query": "label_values(dockerstats_cpu_percent,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dockerstats_cpu_percent{name=~\"$cname\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dockerstats_mem_percent{name=~\"$cname\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage (GB)",
   "type": "timeseries",
   "description": "Red dash line is their limit.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "dockerstats_mem_usage{name=~\"$cname\"} / 1000000000",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "dockerstats_mem_limit{name=~\"$cname\"} / 1000000000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "description": "Blue is receiving, Yellow is transferring",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "dockerstats_net_rx{name=~\"$cname\"} / 1000000",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "dockerstats_net_tx{name=~\"$cname\"} / 1000000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "description": "Blue is read, Yellow is write",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "dockerstats_blk_read{name=~\"$cname\"} / 1000000",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "dockerstats_blk_write{name=~\"$cname\"} / 1000000",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}